<a href="https://colab.research.google.com/github/tnalsdk111/SKN13_Sumin/blob/main/02_tensor_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor 생성
- 파이토치에서 데이터를 저장하는 자료구조
- ndarray와 성격, 사용법이 유사하다. (numpy)

> **pytorch의 tensor는 숫자 데이터 타입만 지원한다.**

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - 지정한 dtype(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
    - torch는 모듈, tensor는 함수
      
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다.
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)**
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수



In [ ]:
import torch
import numpy as np

In [ ]:
np.array([1, 2, 3], dtype=np.int8)#"int8")

array([1, 2, 3], dtype=int8)

numpy 자료구조의 경우 dtype은 "int8"과 같이 문자열로 지정해줄 수도 있다.
근데 torch는 안 돼용

> 인용구 추가



In [ ]:
print('torch Data types')
print("float:", torch.float16, torch.float32, torch.float64, torch.float, torch.double)  #torch.float: float32
print("int:", torch.int8, torch.int16, torch.int32, torch.int64, torch.short, torch.int, torch.long)# 가능
print("uint:", torch.uint8, torch.uint16, torch.uint32, torch.uint64)
print("bool:", torch.bool)

torch Data types
float: torch.float16 torch.float32 torch.float64 torch.float32 torch.float64
int: torch.int8 torch.int16 torch.int32 torch.int64 torch.int16 torch.int32 torch.int64
uint: torch.uint8 torch.uint16 torch.uint32 torch.uint64
bool: torch.bool


In [ ]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)


print("shape:", a.shape, a.size())
print("0축 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)  # type(): Tensor 객체 타입. dtype: data type => 둘은 좀 다르다.
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device)  # tensor를 다루는 processor(메모리위치) - cpu, cuda(gpu)

shape: torch.Size([2, 2]) torch.Size([2, 2])
0축 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


- device: cpu => RAM 쓰고 있구나~


- gpu => VRAM 쓰고 있구나~

type은 클래스 객체 타입, dtype은 데이터 타입을 의미함.

In [ ]:
aa = torch.tensor(range(10))
print(aa)
aa.type()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


'torch.LongTensor'

In [ ]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
# c = torch.IntTensor([10,20,30])    # int32
# print(c.dtype)
# d = torch.DoubleTensor([1, 2, 3])  # float64
# print(d.dtype)
# e = torch.LongTensor([10, 20, 30]) # int64
# print(e.dtype)

torch.float32


## 동일한 값을 원소로 가지는 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(size, fill_value), full_like(텐서, fill_value)**: 지정한 값으로 구성된 tensor생성
  - size
    - shape을 지정한다.
    - zeros, ones는 가변인자이므로 축별 size를 순서대로 서정
    - full 은 tuple/list로 shape을 지정한다.
    

In [ ]:
# a = torch.zeros(3,2,3) # 3 x 2 x 3
# print(a.dtype)
# a
# torch.ones(2,3)  # 2 X 3
torch.full([3,2], fill_value=100) # 3 x 2

tensor([[100, 100],
        [100, 100],
        [100, 100]])

In [ ]:
# 특정 배열과 동일한 shape의 tensor 생성.
a = torch.tensor([[1, 2],[3, 4]]) # 2 x 2

print(a.shape)
b = torch.zeros_like(a)  # a와 같은 shape, dtype 으로 생성.
# b = torch.ones_like(a)
# b = torch.full_like(a, 20)
print(b.shape, b.dtype)
b

torch.Size([2, 2])
torch.Size([2, 2]) torch.int64


tensor([[0, 0],
        [0, 0]])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)**
- **torch.linspace(start, end, steps,)** : steps - 원소개수

In [ ]:
torch.arange(10)  # end. 0 ~ 10-1 1씩 증가
# torch.arange(0, 1, 0.1) # 0 ~ 1-0.1, 0.1
# torch.arange(10, 1, -1) # 10 ~ 1-(-1), -1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(0, 10, 5) # 0 ~ 10, 5개원소
torch.linspace(0, 1, 11)


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**

In [ ]:
torch.empty(3,2,7) # 3 X 2 X 7

tensor([[[1.3298e-17, 4.4536e-41, 1.8249e-32, 0.0000e+00, 4.7659e-34,
          4.4536e-41, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 9.1835e-41, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])

빈 텐서를 만드는데, 안을 비워놓을 수는 없어서 -> 0에 가까운 값들로 임의로 채워넣는다. zeros랑 비슷함. 이런 게 있다는 것만 알아두자~~

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n-1 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [ ]:
torch.manual_seed(0)  # seed 설정
# torch.rand(1, 3, 5) # 100 x 3 x 5
# torch.randn(30, 3) # 30 X 3
# torch.randint(1, 100, (3, 3, 6))
torch.randperm(100) # 0 ~ 99 를 섞어서 구성 # 인덱스 만들 때 자주 쓴다.

tensor([44, 19, 93, 90, 71, 69, 37, 95, 53, 91, 81, 42, 80, 85, 74, 56, 76, 63,
        82, 40, 26, 92, 57, 10, 16, 66, 89, 41, 97,  8, 31, 24, 35, 30, 65,  7,
        98, 23, 20, 29, 78, 61, 94, 15,  4, 52, 59,  5, 54, 46,  3, 28,  2, 70,
         6, 60, 49, 68, 55, 72, 79, 77, 45,  1, 32, 34, 11,  0, 22, 12, 87, 50,
        25, 47, 36, 96,  9, 83, 62, 84, 18, 17, 75, 67, 13, 48, 39, 21, 64, 88,
        38, 27, 14, 73, 33, 58, 86, 43, 99, 51])

In [ ]:
a = torch.arange(100)
a
# a 섞기
idx = torch.randperm(100) # 0 ~ 99 섞어서 반환. -> index
idx
b = a[idx]
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
idx

tensor([55, 28, 72, 48, 42, 52,  2, 18, 19, 38, 41, 34, 17, 95, 23, 73, 29, 80,
         9,  7, 93, 46, 13, 58, 16, 10,  8, 40, 67, 74, 82, 99, 98, 26, 68, 59,
        39, 64,  6, 24, 79, 89, 15, 45, 51, 63,  0, 86, 91, 11, 87, 12, 53, 85,
        76, 65, 49,  3, 92,  5, 61, 77, 90, 30, 78, 37, 21, 57, 33, 60, 75, 66,
        22, 96,  4, 69, 97, 20, 47, 83, 27, 43,  1, 35, 88, 62, 44, 32, 50, 31,
        14, 71, 70, 25, 56, 54, 94, 36, 81, 84])

In [ ]:
b

tensor([55, 28, 72, 48, 42, 52,  2, 18, 19, 38, 41, 34, 17, 95, 23, 73, 29, 80,
         9,  7, 93, 46, 13, 58, 16, 10,  8, 40, 67, 74, 82, 99, 98, 26, 68, 59,
        39, 64,  6, 24, 79, 89, 15, 45, 51, 63,  0, 86, 91, 11, 87, 12, 53, 85,
        76, 65, 49,  3, 92,  5, 61, 77, 90, 30, 78, 37, 21, 57, 33, 60, 75, 66,
        22, 96,  4, 69, 97, 20, 47, 83, 27, 43,  1, 35, 88, 62, 44, 32, 50, 31,
        14, 71, 70, 25, 56, 54, 94, 36, 81, 84])

In [ ]:
b.device

device(type='cpu')

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부
        - False 나오면 못쓴다는 뜻

In [ ]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# device = 'mps' if torch.backends.mps.is_available() else 'cpu'
# device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'cuda'

로컬 컴퓨터에서는 CPU가 나온다. mac에서는 mps

런타임 유형 GPU로 변경하면 기존에 쓰던 컴퓨터는 반납되고 GPU 쓸 수 있는 컴퓨터를 빌려온다. -> 기존 연결은 끊어진다.

In [ ]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device) #생성할 때 device 지정.
print(t, t.device) # tensor가 어느 device에 있는지 확인

tensor([1., 2., 3.], device='cuda:0') cuda:0


cuda:0은 0번째 gpu(=첫번째)라는 뜻. 현재 gpu 하나밖에 없으니 0이 나오는 것임.

In [ ]:
t2 = t.to("cpu")  # 다른 device로 옮기기.
print(t2, t2.device)

tensor([1., 2., 3.]) cpu


In [ ]:
t3 = t2.to("cuda")
print(t3, t3.device)

tensor([1., 2., 3.], device='cuda:0') cuda:0


런타임 다시 CPU로 옮길게용 아래는 gpu 필요 없어서~ ~~귀찮으면 GPU 유료결제~~

## tensor를 상수로 변환
- torch.Tensor객체를 파이썬 상수로 변환.
- tensor객체.item()
    - Scalar(상수) 또는 원소가 하나인 tensor를 python 상수로 변환

In [ ]:
import torch

In [ ]:
print(torch.tensor(30)) # 0차원 텐서 (상수)

tensor(30)


pytorch에 0차원 tensor 30이 있는데, 이걸 빼서 python int형 30으로 만드려고 한다. 단, [10, 20]과 같이 값이 여러 개 있으면 안 된다.

item()을 이용해 원소를 뽑아보아요

In [ ]:
a = torch.tensor(10)  # 상수(scalar) => 0차원 Tensor
print(a, a.ndim) # 0차원
print(a.item())
print(type(a), type(a.item()))

tensor(10) 0
10
<class 'torch.Tensor'> <class 'int'>


tensor(10) -> 10으로 빼준다. python int 타입으로!!

In [ ]:
b = torch.tensor([[20]]) # 원소가 하나인 N차원 배열
print(b, b.dim())
print(b.item()) #원소가 하나인 배열(텐서) 변환 가능

tensor([[20]]) 2
20


In [ ]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


c처럼 원소가 두 개 이상이면 안 됩니다.

In [ ]:
d = torch.tensor([10], device='cuda')
print(d)
print(d.item())

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [ ]:
import numpy as np
import torch

In [ ]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr, dtype=torch.float32)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.to("cpu").numpy()

tensor([[ 0.2517, -0.9471, -0.0636],
        [-0.3745, -0.1760, -0.3322],
        [ 0.2072,  1.7419,  0.6559]])


array([[ 0.25173888, -0.9470678 , -0.06356384],
       [-0.37448442, -0.17597902, -0.3322332 ],
       [ 0.20716366,  1.7419001 ,  0.65588737]], dtype=float32)

In [ ]:
# t2 = torch.randn(2,2, device="cuda")
# t2

In [ ]:
# t2.numpy()
# t2.to("cpu").numpy()

# 원소 조회및 변경

## indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>** => 역순 조회가 안 된다.


딥러닝은 데이터셋이 워낙 크니까 데이터를 조회할 일이 별로 없으나.. 조회 한 번 해볼게요잉

In [ ]:
t = torch.randint(-10, 10, (100, ))
t

tensor([  2,  -4,  -6,  -1,   5,  -1,  -2, -10,   8,  -3,   6,  -6,  -5,   0,
          3,  -8,  -6,   7,   5,   0,   1,  -8,   8,  -3,   2,   2,  -1,   9,
         -6,  -6,  -9,  -1,   4,  -2,   4,   2,   6,  -1,   0,  -3,   2,  -4,
          9,  -8,  -9,  -3,  -2,   0,   3,   4,   3,   7,   6,  -2,   5,  -8,
          0,   0,   3,   6,   7,  -2,   3,  -4,   8,   1,  -6,   4,   4, -10,
         -4,   6,  -5,   3,  -2,   6,   2,   6,   7,   6,   3,  -5,  -2,   7,
         -2,  -4,   7,   3,  -6,   8,   0,  -1,   8,  -7,   6,   7, -10,  -2,
         -9,   9])

In [ ]:
t[0]
# t[[1, 5, -1]] # 여러개 조회-> fancy indexing

tensor(2)

In [ ]:
t[:5]
# t[10:15]
# t[90:]
# t[3:30:3]

####### step 음수 안된다. 그래서 reverse(역순 조회)가 안됨. reverse하려면 flip() 사용
# t[10:1:-2]
t[1:10:2].flip(dims=(0,)) #reverse

tensor([ -3, -10,  -1,  -1,  -4])

위는 역순, 아래는 원본

In [ ]:
t[1:10:2]

tensor([ -4,  -1,  -1, -10,  -3])

## boolean index
- 논리 연산은 &, |, ~ 을 사용한다.

In [ ]:
# boolean index
t[t > 0] # 0보다 큰 원소를 조회한다.

tensor([2, 5, 8, 6, 3, 7, 5, 1, 8, 2, 2, 9, 4, 4, 2, 6, 2, 9, 3, 4, 3, 7, 6, 5,
        3, 6, 7, 3, 8, 1, 4, 4, 6, 3, 6, 2, 6, 7, 6, 3, 7, 7, 3, 8, 8, 6, 7, 9])

elementwise 연산 지원 => 원소별로 T/F가 나온다.

In [ ]:
t[(t > 0) & (t < 5)]

tensor([2, 3, 1, 2, 2, 4, 4, 2, 2, 3, 4, 3, 3, 3, 1, 4, 4, 3, 2, 3, 3])

논리연산자로 &(and), |(or), ~(not)을 쓸 수 있다. python에서 쓰던 and, or 이런 건 못 쓴다.

In [ ]:
# boolean index 처리 함수.
t.masked_select(t > 0)

tensor([2, 5, 8, 6, 3, 7, 5, 1, 8, 2, 2, 9, 4, 4, 2, 6, 2, 9, 3, 4, 3, 7, 6, 5,
        3, 6, 7, 3, 8, 1, 4, 4, 6, 3, 6, 2, 6, 7, 6, 3, 7, 7, 3, 8, 8, 6, 7, 9])

In [ ]:
t

tensor([  2,  -4,  -6,  -1,   5,  -1,  -2, -10,   8,  -3,   6,  -6,  -5,   0,
          3,  -8,  -6,   7,   5,   0,   1,  -8,   8,  -3,   2,   2,  -1,   9,
         -6,  -6,  -9,  -1,   4,  -2,   4,   2,   6,  -1,   0,  -3,   2,  -4,
          9,  -8,  -9,  -3,  -2,   0,   3,   4,   3,   7,   6,  -2,   5,  -8,
          0,   0,   3,   6,   7,  -2,   3,  -4,   8,   1,  -6,   4,   4, -10,
         -4,   6,  -5,   3,  -2,   6,   2,   6,   7,   6,   3,  -5,  -2,   7,
         -2,  -4,   7,   3,  -6,   8,   0,  -1,   8,  -7,   6,   7, -10,  -2,
         -9,   9])

In [ ]:
# 변경
t[0] = 100
t

tensor([100,  -4,  -6,  -1,   5,  -1,  -2, -10,   8,  -3,   6,  -6,  -5,   0,
          3,  -8,  -6,   7,   5,   0,   1,  -8,   8,  -3,   2,   2,  -1,   9,
         -6,  -6,  -9,  -1,   4,  -2,   4,   2,   6,  -1,   0,  -3,   2,  -4,
          9,  -8,  -9,  -3,  -2,   0,   3,   4,   3,   7,   6,  -2,   5,  -8,
          0,   0,   3,   6,   7,  -2,   3,  -4,   8,   1,  -6,   4,   4, -10,
         -4,   6,  -5,   3,  -2,   6,   2,   6,   7,   6,   3,  -5,  -2,   7,
         -2,  -4,   7,   3,  -6,   8,   0,  -1,   8,  -7,   6,   7, -10,  -2,
         -9,   9])

In [ ]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# t[ 0축, 1축 ]
t[1, 2].item() # 6
t[0, 2].item() # 3

3

In [ ]:
t[[1,0], [2,2]]  #(1,2), (0,2)
# t[[첫번째값, 두번째값]-0축, [첫번째값, 두번째값]-1축]

tensor([6, 3])

# Reshape

## shape 변경
- tensor객체.reshape(\*shape) / view(\*shape) 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
    - shape 변환하는 건 얕은 복사. 만약 12 x 1 a를 3 x 4 b로 바꾼다면 -> b는 a의 shape을 바꿔서 '보여주는 것'임. 즉 b에서 원소 값을 변경하면 a 값도 변경된다. 이를 막으려면 deep copy를 해야하고, clone()을 통해 할 수 있다.
 > tensor.clone(): tensor를 복제한다.

In [ ]:
a=torch.rand(12) # (12,)
a2 = a.reshape(3,4)
a3 = a.reshape((3,2,2))
a4 = a.reshape((3,2,-1))  #한 개 axis는 -1로 설정가능하고 그럼 계산해서 알아서 설정해 준다.
print(a.shape, a2.size(), a3.shape, a4.shape)


torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [ ]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [ ]:
# a5[0, 0] = 12.1
a2[0, 1] = 15.1

print(a2)

tensor([[ 0.7615, 15.1000,  0.9977,  0.7697],
        [ 0.5953,  0.1529,  0.0965,  0.2169],
        [ 0.2511,  0.2488,  0.2611,  0.1998]])


In [ ]:
# tensor복사: clone() 메소드
r = a.reshape(3, 4).clone()
r[0,0] = 100.1
print(a)

tensor([ 0.7615, 15.1000,  0.9977,  0.7697,  0.5953,  0.1529,  0.0965,  0.2169,
         0.2511,  0.2488,  0.2611,  0.1998])


In [ ]:
r

tensor([[1.0010e+02, 1.5100e+01, 9.9771e-01, 7.6966e-01],
        [5.9532e-01, 1.5285e-01, 9.6542e-02, 2.1690e-01],
        [2.5109e-01, 2.4881e-01, 2.6111e-01, 1.9983e-01]])

## dummy 축 늘리기

- None을 이용 (numpy의 newaxis 대신 None을 사용한다.)
- unsqueeze(dim=축번호)

numpy에서는 a[np.na, ...] 이런 식으로 '...'을 붙여 만들어주었죠? tensor에서는 이 방식을 지원하지 않습니다. 대신 None을 사용하고 :를 사용한다.

In [ ]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

# 앞에 더미축, 뒤는 그대로
# None이 dummy, :는 그대로 넣어준다는 뜻
a1, a2 = a[None, :], a.unsqueeze(dim=0) # dim=정수만가능
print(a1.shape, a2.shape)

# 앞은 그대로, 뒤는 더미축이라면 다르다
# 축별로 :를 각각 넣어야 한다.
# a[:, :, None]: 0번 축 그대로(2), 1번 축 그대로(2), 2번 축 더미(1)
# 이때는 unsqueeze를 쓰는 게 더 편하다
a3, a4 = a[:, :, None], a.unsqueeze(dim=-1)   # a[:, None] # 0축 :, 1축 None, 2번축 지정안함 -> 원래대로 그래서 (2, 1, 2) 가됨.
print(a3.shape, a4.shape)

# a5, a6 = a3[:,None,:,:, None],  a3.unsqueeze(dim=1)  # unsqueeze(): dim=정수만가능 (한번에 dummy축은 하나만 추가가능.)
# print(a5.shape, a6.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용

In [ ]:
t = torch.rand(3, 1, 4, 1, 5, 1)
print(t.shape)
#print(t)

r1 = t.squeeze()  #축을 명시 하지 않으면 모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 4, 1, 5, 1])
torch.Size([3, 4, 5])
torch.Size([3, 4, 1, 5, 1])
torch.Size([3, 4, 5, 1])


# tensor 합치기
torch.cat([tensorA, tensorB, ...], dim=0) : 기준축 default 는 0

합치려고 하는 기준축이 있으면 나머지 축은 size가 다 같아야 함

(3, 4, 5, 6)과 (5, 4, 5, 6)을 0번 축 기준으로 합친다면 = (8, 4, 5, 6)

나머지 축으로는 합칠 수 없다.

In [ ]:
a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(20,30).reshape(2,5)
d = torch.arange(10,19).reshape(3,3) # 얘만 shape이 달라요

합칠 때는 cat() 함수를 쓰면 됩니다.

In [ ]:
torch.cat([a, b], dim=0) # a와 b를 0번 축으로 합칠 것이다.

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

(2, 5)와 (2, 5)를 0번 축 기준으로 합친다 => (2+2, 5)

둘 다 1번 축이 5라서 가능한 것임.

In [ ]:
torch.cat([a, b, c], dim=0) # 6 X 5

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [ ]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

numpy에서 axis를 쓰거든요.. 축이 0번이든 1번이든 상관없이 axis 써도 ㄱㅊ

In [ ]:
torch.cat([a, b, c], axis=1)

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [ ]:
torch.cat([a, b], axis=-1)  # -1: 마지막 axis

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
a.shape, d.shape
# 합치는 기준축 이외의 축 size는 같아야 한다.
# torch.cat([a, d])  #dim=0, Error  1축 size가 달라서 Error
# 0번 축을 붙이는 거니까 0번 축끼리는 달라도 괜찮은데, 1번 축은 같아야 함.

(torch.Size([2, 5]), torch.Size([3, 3]))

# 값의 위치(index) 변경
- tensor 원소의 index의 위치를 바꾼다.
- `tensor.transpose(axis1, axis2)`
    - 두 축의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - 두 개 이상의 축 자리를 변경한다.

- 넘파이에서는 transpose만 지원, tensor는 위 두 가지를 다 지원한다.

reshape하고는 다르다. 값의 '위치' 자체를 바꾸는 것임.

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)

y = X.transpose(1, 2) # 1번 축과 2번 축을 바꿔라.
print(y.shape)

z = X.permute(2, 0, 1)
print(z.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
torch.Size([4, 2, 3])


In [ ]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
y

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

X에서 21은 [1, 2, 1] 위치에 있었음

그런데 y에서는 1번 축과 2번 축의 인덱스를 바꾼 거니까
[1, 1, 2]가 된다.

shape만 보는 게 아니라 값도 봐야 한다.

numpy에서는 transpose로 다 했다면, tensor는 transpose와 permute 둘 다 사용한다.

# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산자 **tensor간에 shape이 같아야 한다.**
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

(3, 2)와 (2,)를 연산 -> broadcasting 연산: (3, 2)와 (1, 2) - 차원이 적은 쪽 앞에 더미 축을 추가한다.

In [ ]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


원소별로 연산한다~~

In [ ]:
print(a + 100)
print(a - 100)
print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])
tensor([[-100,  -99,  -98,  -97,  -96],
        [ -95,  -94,  -93,  -92,  -91]])
tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False]])


In [ ]:
print(a + b)
print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [ ]:
a.size(), c.size()

(torch.Size([2, 5]), torch.Size([5]))

In [ ]:
# broadcasting
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


(2, 5) + (5,) => (2, 5) + (1, 5)

마치 상수를 더하듯이 처리해주겠다

## 주요 연산함수

### 주요 상수
#### 자연상수 E

In [ ]:
torch.e, np.e, torch.pi, np.pi

(2.718281828459045, 2.718281828459045, 3.141592653589793, 3.141592653589793)

#### torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한.
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [ ]:
print(torch.inf > 10000000000000000, torch.inf < 10000000000)
print(-torch.inf < -1000000000000000000000, -torch.inf > 10)


True False
True False


In [ ]:
print(torch.log(torch.tensor(-1))) # nan (계산결과가 없으므로-없는값-nan 반환)
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


e의 몇 제곱을 해야 -1이 되느냐 -> 계산 불가. nan

## 주요 연산 함수

원소별로 계산한다. (element-wise 계산)

아래는 전부 3x3 형태로 나온다~!

In [ ]:
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x)) # 절대값
print(torch.sqrt(torch.abs(x))) #  제곱근
print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x))) # log에 음수 들어가면 안 되니까 절댓값 취해서 넣어준다.
print(torch.log(torch.exp(torch.tensor(1))))  # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.8316e-02, 4.9787e-02, 1.3534e-01],
        [3.6788e-01, 1.0000e+00, 2.7183e+00],
        [7.3891e+00, 2.0086e+01, 5.4598e+01]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.)
tensor(1.)
tensor(1.)


In [ ]:
y = x + torch.randn((3,3))
print(y)
print(torch.round(y)) # 반올림
print(torch.round(y, decimals=2)) # 소수점 둘째자리 이하에서 반올림
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림

tensor([[-3.5758, -3.0718, -1.3374],
        [-2.6256,  0.5567,  1.2187],
        [ 0.7943,  2.4605,  3.0070]])
tensor([[-4., -3., -1.],
        [-3.,  1.,  1.],
        [ 1.,  2.,  3.]])
tensor([[-3.5800, -3.0700, -1.3400],
        [-2.6300,  0.5600,  1.2200],
        [ 0.7900,  2.4600,  3.0100]])
tensor([[-4., -4., -2.],
        [-3.,  0.,  1.],
        [ 0.,  2.,  3.]])
tensor([[-3., -3., -1.],
        [-2.,  1.,  2.],
        [ 1.,  3.,  4.]])


In [ ]:
# 필기를 꼼꼼히 본 프린세스만 볼 수 있는 코드
# 오늘 점심 오봉집 먹을 거야 히힛!

decimal을 양수로 주면 소수점 쪽으로 내려가고, 음수로 주면 정수 쪽으로 올라간다.

### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용 (matrix multiply)

In [ ]:
import torch

In [ ]:
x = torch.FloatTensor([[1, 2],[3, 4],[5, 6]])

y = torch.FloatTensor([[1, 2],[1, 2],])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

x의 열 2 = y의 행 2 => 행렬 곱 연산이 가능하다.

In [ ]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
y

tensor([[1., 2.],
        [1., 2.]])

z1, z2 연산 결과는 동일하다.

In [ ]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [ ]:
# Batch 행렬곱(Batch matrix muliplication) - bmm()
# 피연산자로 두개의 3차원 tensor를 axis (1, 2)를 기준으로 행렬곱을 처리한다.
import torch
x = torch.FloatTensor(3,4,2) # 4 x 2 짜리가 3개씩 있다
y = torch.FloatTensor(3,2,5) # 2 x 5 짜리가 3개씩 있다
# 4x2, 2x5는 연산 가능 => element-wise 연산
z = torch.bmm(x, y)
z.shape
# 결과적으로 4x5짜리가 3개가 나온다.

torch.Size([3, 4, 5])

## 기술통계함수

In [ ]:
X=torch.randn(3,4)
print(X)

tensor([[ 0.7609,  1.1464,  1.1595, -1.2916],
        [-0.2028,  0.5914, -0.6485, -0.5638],
        [ 0.5058, -1.2843,  0.5818,  0.7728]])


In [ ]:
print(torch.sum(X))  # default: 전체기준으로 계산. dim=None
print(torch.sum(X, dim=1)) #dim/axis 지정: 지정한 axis의 index가 다른 값끼리 계산.
print(torch.sum(X, dim=1, keepdims=True)) # 기술통계함수들을 실행하면 차원이 줄어든다. keepdims=True로 하면 차원유지

tensor(1.5277)
tensor([ 1.7752, -0.8237,  0.5761])
tensor([[ 1.7752],
        [-0.8237],
        [ 0.5761]])


In [ ]:
print(torch.mean(X))
print(torch.mean(X, dim=0))
print(torch.mean(X, dim=0, keepdims=True)) # 2차원으로

tensor(0.1273)
tensor([ 0.3546,  0.1512,  0.3643, -0.3609])
tensor([[ 0.3546,  0.1512,  0.3643, -0.3609]])


In [ ]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance
print(torch.var(X, dim=0))

tensor(0.8884)
tensor(0.7892)
tensor([0.2493, 1.6225, 0.8527, 1.0964])


In [ ]:
# tensor.메소드()
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[ 1.7752],
        [-0.8237],
        [ 0.5761]])
tensor([[ 0.4438],
        [-0.2059],
        [ 0.1440]])
tensor(0.8884)


In [ ]:
X

tensor([[ 0.7609,  1.1464,  1.1595, -1.2916],
        [-0.2028,  0.5914, -0.6485, -0.5638],
        [ 0.5058, -1.2843,  0.5818,  0.7728]])

dim=0: 맨 안 쪽 (열)
dim=1: 그 바깥쪽 (행)

In [ ]:
print(torch.max(X)) # dim을 지정하지 않으면 전체 기준 max값 계산.
print(torch.max(X, dim=0))  # 축을 지정하면 return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
print(torch.max(X, dim=1))
print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ") # 값과 인덱스 각각 추출


# print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
# print(torch.max(X, dim=1, keepdims=True))

tensor(1.1595)
torch.return_types.max(
values=tensor([0.7609, 1.1464, 1.1595, 0.7728]),
indices=tensor([0, 0, 0, 2]))
torch.return_types.max(
values=tensor([1.1595, 0.5914, 0.7728]),
indices=tensor([2, 1, 3]))
tensor([1.1595, 0.5914, 0.7728]) || tensor([2, 1, 3])


In [ ]:
print(torch.min(X))
print(torch.min(X, dim=0)) # return_types.min 타입객체로 반환. min값과 min값의 index를 묶어서 반환
# print(torch.min(X, dim=1))

tensor(-1.2916)
torch.return_types.min(
values=tensor([-0.2028, -1.2843, -0.6485, -1.2916]),
indices=tensor([1, 2, 1, 0]))


In [ ]:
print(torch.argmax(X)) # 전체 중 가장 큰 값의 index -> flatten(1차원으로변환)한 뒤 index를 반환. # 1.1595
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor(2)
tensor([0, 0, 0, 2])
tensor([2, 1, 3])


In [ ]:
a = torch.max(X, dim=0)
print(a.values)
print(a.indices)

tensor([0.7609, 1.1464, 1.1595, 0.7728])
tensor([0, 0, 0, 2])


# autograd(자동미분) ⭐
- 자동 미분을 이용해 gradient(미분계수)를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면(gradient 계산 대상 변수) `requires_grad=True` 로 설정되 있어야 한다. (default: False)

> - **미분**
>   -  (순간) 변화율을 계산한다.
>   - $$\frac{\partial y}{\partial x}$$
>       - x에 대한 y의 변화율. 즉 x가 변하면 y는 얼마나 변할까?

In [ ]:
import torch

In [ ]:
x = torch.tensor([1, 0])
print(x.requires_grad) # x가 gradient를 구해야 하는 애야? (False)

False


x 텐서 안에 있는 거: data, r_grad, grad

In [ ]:
# Gradient를 계산할 대상인지 여부
## True: x를 이용한 계산을 할 때 gradient 함수(도함수)를 정의해서 저장한다.
x = torch.tensor([1.0], requires_grad=True)
print(x.requires_grad) # x가 gradient를 구해야 하는 애야? (False)
# x.requires_grad = True # 속성이라서 나중에 바꿀 수 있어요.

True


In [ ]:
# Tensor의 속성
## data - Tensor가 가지는 값들을 저장하는 변수(속성)
print(x.data) # tensor([1.])
## grad - Gradient 값을 저장하는 변수(속성)
print(x.grad)

tensor([1.])
None


In [ ]:
y = x**2
y # tensor([1.], grad_fn=<PowBackward0>)
# 도함수를 생성해 y에 저장

tensor([1.], grad_fn=<PowBackward0>)

In [ ]:
y.grad_fn # gradient 게산함수(도함수)가 저장된 변수(속성)
# dy/dx (x(requires_grad=True)에 대한 y의 변화율)을 저장한 것임.

y = x ** 2이니까

y.grad_fn = 2 * x가 저장된 것임

In [ ]:
# gradient 계산
y.backward()
## dy/dx(x의 변화에 대한 y의 변화율)을 계산해 그 결과를 x.grad에 저장한다.

In [ ]:
x.grad

tensor([2.])

In [ ]:
x.data, x.grad, y.grad_fn
# (tensor([1.]), tensor([2.]), <PowBackward0 at 0x7af3b87036d0>)

(tensor([1.]), tensor([2.]), <PowBackward0 at 0x7af3b87036d0>)

data 1.0을 y_grad(2\*x)를 통해 계산 -> 2 * 1.0 = 2.0 -> 이 값을 **x.grad**에 넣음

In [ ]:
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([3.0])
c = a**2 + b**3 # grad_fn 생성
c.backward() # gradient를 계산한다.

c는 a에 대해서만 gradient를 계산한다. a만 requires_grad = True이기 때문이다.

In [ ]:
c.grad_fn, a.data, a.grad
# (<AddBackward0 at 0x7af39f597c70>, tensor([2.]), tensor([4.]))

(<AddBackward0 at 0x7af39f597c70>, tensor([2.]), tensor([4.]))

In [ ]:
b.grad # None -> 아무것도 안 나옴
print(b.grad)

None


In [ ]:
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([3.0], requires_grad=True)
c = a**2 + b**3 # grad_fn 생성
c.backward() # gradient를 계산한다.

In [ ]:
c.grad_fn, a.data, a.grad
# (<AddBackward0 at 0x7af39f597c70>, tensor([2.]), tensor([4.]))

(<AddBackward0 at 0x7af39f4cefe0>, tensor([2.]), tensor([4.]))

In [ ]:
c.grad_fn, b.data, b.grad
# (<AddBackward0 at 0x7af39f597c70>, tensor([3.]), tensor([27.]))
# 도함수는 3 * b^2 => 3 * 3^2 = 27

(<AddBackward0 at 0x7af39f4cefe0>, tensor([3.]), tensor([27.]))

In [ ]:
# 간단한 경사하강법 구현
input_data = torch.tensor([30.2]) # x
output_data = torch.tensor([10.5]) # y

weight = torch.tensor([0.2], requires_grad=True) # parameter
y_pred = weight * input_data # 모델 예측값

loss = (output_data - y_pred)**2 # 오차계산. MSE (여기서는 데이터가 하나밖에 없음)

In [ ]:
loss # 19.8916

tensor([19.8916], grad_fn=<PowBackward0>)

In [ ]:
y_pred # 6.0400

tensor([6.0400], grad_fn=<MulBackward0>)

In [ ]:
y_pred.grad_fn, loss.grad_fn

(<MulBackward0 at 0x7af39f2c2e60>, <PowBackward0 at 0x7af39f2c1450>)

1. weight: requires_grad = True

2. y_pred도 r_grad = True가 된다.

3. loss도 r_grad = True가 된다.

loss <- y_pred <- weight

우리는 마지막 최종 함수에만 backward()를 걸어주면 된다 => `loss.backward()`

In [ ]:
loss.backward()

In [ ]:
weight.grad

tensor([-269.3840])

In [ ]:
new_weight = weight.data - weight.grad * 0.0001
# weight.data: 현재 weight
# weight.grad: 계산한 거
# 0.0001: 학습률
new_weight

tensor([0.2269])

chain rule

dL/dw = dL/dy * dy/dw

## torch.no_grad()
- no_grad()를 with 구문에서 연산을 할 경우 with block 내에서 requires_grad=True로 설정된 변수를 이용한 계산식이 있더라도 grad_fn을 생성하지 않는다. 즉 gradient를 계산하지 않는다.
- 딥러닝 모델을 평가 하거나 추론을할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.


In [ ]:
x = torch.tensor([1.0], requires_grad=True)
y = x**2
print("결과:", y.data)
print("grad_fn:", y.grad_fn)

결과: tensor([1.])
grad_fn: <PowBackward0 object at 0x7af39f5953c0>


In [ ]:
with torch.no_grad():
  y = x**2
  print("결과:", y.data)
  print("grad_fn:", y.grad_fn) # r_grad=False가 되면서 grad_fn이 None이 된다.

결과: tensor([1.])
grad_fn: None


예제~

In [ ]:
x = torch.tensor([1.0], requires_grad=True)
print(x.grad)
y = x**2
y.backward()
print(x.grad)

None
tensor([2.])


In [ ]:
# x를 이용한 새로운 계산\
x.grad = None # 초기화
# GRAD 값을 초기화 하지 않으면 이전 계산된 grad 값이 남아있게 된다.
# 그리고 새로운 grad 값을 구하게 되면 기존 값에 더한다.
# 이 경우 2.0 + 3.0 + 3.0 = 8.0
z = x ** 3
z.backward() # 3 * x^2

In [ ]:
print(x.grad)

tensor([3.])


gradient를 계속 누적 시킨다. 2.0 + 3.0 (계산값) + 2.0 + 3.0 + 3.0

## gradient 값 초기화
- backward() 에서 계산되어 저장된 gradient값을 초기화한다.
- 반복 학습을 할 경우 gradient가 누적되는 문제가 발생한다. 그래서 한번 학습이 끝나면 다음 학습 전에 초기화하는 작업을 해야 한다.